### ISSUE TITLE
May not build properly if theme is a submodule

### ISSUE THREAD

**Issue by victoriadrake** [victoriadrake/hugo-remote#1]
The [checkout action](https://github.com/actions/checkout) may [not yet fully support submodules](https://github.com/actions/checkout/issues/81). If your site only seems to partially build and is missing pages like `index.html`, you may need to explicitly pull the theme in your workflow file.

Here's an example that adds the step "Get theme" to clone a theme repository into `themes/`:

```yaml
name: hugo-remote

on:
  push:
    branches:
      - master

env:
  REMOTE: opengitdocs/opengitdocs.github.io.git
  DEST: public
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 🛎 Check out master
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: 🖌️ Get theme
        run: git clone https://github.com/opengitdocs/hugo.git themes/opengitdocs
      - name: 🚀 Build and deploy
        uses: victoriadrake/hugo-remote@master
```
