### ISSUE TITLE
Error: failed to download modules: exec: "go": executable file not found in $PATH

### ISSUE THREAD

**Issue by huangbaihua001** [victoriadrake/hugo-remote#13]
#When the action is executed, the following error is reported: 

## Error: failed to download modules: exec: "go": executable file not found in $PATH

here is my workflow yml:

```
name: hugo-remote

on:
  push:
    branches:
      - master

env:
  REMOTE: huangbaihua001/hbh.github.io
  DEST: public
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 🛎 Check out master
        uses: actions/checkout@master
        with:
          fetch-depth: 1
          # if your chosen Hugo theme is a submodule
          submodules: false
      - name: 🚀 Build and deploy
        env:
          HUGO_ARGS: '--minify --cleanDestinationDir'
        uses: victoriadrake/hugo-remote@v1.1

```

Build and deploy log:
```
15s
Run victoriadrake/hugo-remote@v1.1
/usr/bin/docker run --name e435d3019d69a849fe84724a4d7236f63b_716028 --label 5588e4 --workdir /github/workspace --rm -e REMOTE -e DEST -e TOKEN -e HUGO_ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/blog/blog":"/github/workspace" 5588e4:35d3019d69a849fe84724a4d7236f63b
🔧 Install tools
Wrote to /github/workspace/package.json:

{
  "name": "workspace",
  "version": "1.0.0",
  "description": "<<<<<<< HEAD # walker",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/huangbaihua001/blog.git"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/huangbaihua001/blog/issues"
  },
  "homepage": "https://github.com/huangbaihua001/blog#readme"
}


npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN postcss-cli@8.3.1 requires a peer of postcss@^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN autoprefixer@10.2.5 requires a peer of postcss@^8.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-reporter@7.0.2 requires a peer of postcss@^8.1.0 but none is installed. You must install peer dependencies yourself.

+ postcss-cli@8.3.1
+ autoprefixer@10.2.5
added 102 packages from 72 contributors and audited 103 packages in 4.512s

14 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

🤵 Install Hugo
LICENSE
README.md
hugo
hugo v0.82.0-9D960784+extended linux/amd64 BuildDate=2021-03-21T17:28:04Z VendorInfo=gohugoio
👯 Clone remote repository
Cloning into 'public'...
🧹 Clean site
🍳 Build site
Total in 3 ms
Error: failed to download modules: exec: "go": executable file not found in $PATH
```
